name: CI

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install deps
        run: npm ci
      - name: build app
        run: npm run build
      - name: tests
        run: npm test
